### ISSUE TITLE
Can't set fan speed

### ISSUE THREAD

**Issue by avaneerd** [Mosibi/whr_930#1]
Hello,

First of all, thanks for this awesome project and the blog post about this. I have been wanting to automate my ventilation unit.

My setup for this is as follows:
 - Zehnder WHR 930 Basic controled with 3-state switch (perilex).
 - Raspberry pi zero with RS232 extension port.
 - Ethernet cable with RJ45 To RS232 converter (with pin mapping 2 -> 3, 3 -> 2, 8 -> 5).
 - Home assistant running in Docker.

It now successfully gets data from the ventilation units and pushes it to Home Assistant.
When I try to change the fan speed (from HA) I see the 'Setting ventilation to x' message appearing in the debug log but unfortunately nothing happens. 

Do you know what goes wrong? Is it because is switched with the 3-state switch?

I appreciate any help I could get with this,

**Comment by Mosibi** [comment]
Hi Alexander,

We have to set the “3-state switch” in the middle position, on ours that’s ‘1’.

**Comment by avaneerd** [comment]
Hi Richard,

I have mainly been testing with the ventilation set to 1, my switch goes from 1 to 3 so the middle position would be 2 for mine. I will do some more testing with this. 

Further on this, do you get a response back when send the commands to set the fan speed? I get no response at all, it seems only the queries get handled and the commands are ignored.

**Comment by Mosibi** [comment]
If have just commited a new version of `whr930.py`  where i changed the set_ventilation_level function to check the returning data for an ACK.

Btw this is our 3-way switch.

![img_1482](https://user-images.githubusercontent.com/3126211/36074677-dc75a3d2-0f43-11e8-95ef-6834e4e99637.JPG)

**Comment by avaneerd** [comment]
Thanks but unfortunately it returns no ACK for me. I tried various things (2 full days) but no result.
Maybe my unit is to old (9-10 years)...

I'm happy enough I can read out the sensor information now, this I can use to switch it with hardware mention here: https://gathering.tweakers.net/forum/list_messages/1645798

**Comment by Mosibi** [comment]
Ok, too bad it's not working for you.

There are more 'set' commands you can try, when you read the PDF i mentioned in my blog. Maybe one of those do work, then you at least know that setting a value is possible.

**Comment by avaneerd** [comment]
Yea I tried a few commands, I thought it had to do with some settings. I tried to use 'RS232 Modus setzen' from the protocol but this also gives me no response.

I also checked if there was a setting in the menu of the unit that could change this, but unfortunately no :(

**Comment by avaneerd** [comment]
Hello Richard,

I wanted to let you know I have booked succes in another way! From the protocol I found that I can use 'Ventilationsstufe setzen' to set the fan speed of the absent level (which is 1 on my switch).

This is the code I used for it
```python
def set_ventilation_speed(vent_in, vent_out):
    speed_in_a = int(vent_in)
	speed_out_a = int(vent_out)
	speed_in_1 = 15
	speed_out_1 = 15
	speed_in_2 = 45
	speed_out_2 = 45
	speed_in_3 = 75
	speed_out_3 = 75
	checksum = 207 + 10 + speed_in_a + speed_out_a + speed_in_1 + speed_out_1 + speed_in_2 + speed_out_2 + speed_in_3 + speed_out_3 + 1 + 1 + 173
	checksum = checksum & 255
    command = "\x07\xF0\x00\xCf\x0a{0}{1}{2}{3}{4}{5}{6}{7}\x01\x01{8}\x07\x0F".format(chr(speed_out_a), chr(speed_out_1), chr(speed_out_2), chr(speed_in_a), chr(speed_in_1), chr(speed_in_2), chr(speed_out_3), chr(speed_in_3), chr(checksum))
	data = serial_command(command)

    if data:
		info_msg('Changed the ventilation to {0}% in and {1}% out'.format(vent_in, vent_out))
    else:
        warning_msg('Changing the ventilation went wrong, did not receive an ACK after the set command'.format(nr))
```

**Comment by Mosibi** [comment]
Hi,

Cool! Still strange that the other command fails with your WHR930.

**Comment by jeroenst** [comment]
When we write the fanspeed levels are these stored in the eeprom/flash of the whr930?

Because that could cause wear-out and causing the WHR930 not to function anymore...

I also would like to know if writing current ventilation level 0x00 0x99 wil write to the eeprom/flash and also cause wear-out.

**Comment by Mosibi** [comment]
Hi @jeroenst,

You are replying to a closed issue, please next time open a new issue.

> When we write the fanspeed levels are these stored in the eeprom/flash of the whr930?

I assume you are talking about the "set_default_fan_speed_levels" function (https://github.com/Mosibi/whr_930/blob/master/src/whr930.py#L362). These values are so called "write commando's" which indeed will be stored in the WHR 930. I think you assumption is right that you should not do this very often

> Because that could cause wear-out and causing the WHR930 not to function anymore...

True. Changing the default fan speed values is not something that you normally would do very often. So in a normal situation where a "write command" is executed once in a while, this will not lead to such an issue.

> I also would like to know if writing current ventilation level 0x00 0x99 wil write to the eeprom/flash and also cause wear-out.

Nope, it is just an instruction that is sent to the WHR930 which is not stored.

**Comment by jeroenst** [comment]
Thank you very much!
