### ISSUE TITLE
UnboundLocalError: local variable 'EnthalpyPresent' referenced before assignment

### ISSUE THREAD

**Issue by iamrellah** [Mosibi/whr_930#10]
Have been running for a couple of days now.
The following error was thrown after not changing the ventilation for a longer period. Then changing the ventilation using the remote control and after a few hours i used home assistant to change the ventilation again. I will try to reproduce if possible but thought it would be best to also post it here. 

```
Traceback (most recent call last):
  File "whr930.py", line 916, in <module>
    sys.exit(main())
  File "whr930.py", line 903, in main
    get_status()
  File "whr930.py", line 777, in get_status
    EnthalpyPresent,
UnboundLocalError: local variable 'EnthalpyPresent' referenced before assignment
```

Edit:
@Mosibi Was able to reproduce the issue. It happens when the remote control is used to set the WHR 930 into a timed mode of 15 minutes on level 3. When the script then tries to retrieve the current state it crashes with the above error.

**Comment by Mosibi** [comment]
I think this one is fixed by https://github.com/Mosibi/whr_930/commit/94e5a07f3b953a0122eb06977efa8a8b62342bf7
