### ISSUE TITLE
WHR 930 Basic model doesn't support all commands

### ISSUE THREAD

**Issue by skamoen** [Mosibi/whr_930#11]
I have a WHR 930 Basic, which supports a subset of the currently implemented commands, but doesn't get all the data as expected. This results in empty values or a KeyError for a number of commands, crashing the program. 

I assume you don't have a spare basic model lying around so I'll try to see if I can implement two different profiles so it only issues supported commands. Expect a PR somewhere this month once I figure out what's supported and what not.

**Comment by Mosibi** [comment]
Hi,

I do not have a spare WHR 930 indeed 😄 Your PR’s are very welcome, especially if it enables to have multiple WHR types. I will close this one, because it is just a PR announcement and not a PR itself.

**Comment by skamoen** [comment]
Seems I was wrong in my assumption that the basic model doesn't support all the commands currently implemented. Not sure what caused the errors in the first place, but after the work done in my PR's, they don't occur anymore.
