### ISSUE TITLE
Q: is there a way to install this module on Hasio? (the os)

### ISSUE THREAD

**Issue by Gompje** [Mosibi/whr_930#15]
My parents recently moved and want to integrate their ventilation system to Home-assistant.

To keep things easy I'm using the hassio os image on a Raspberri pi 4. Now I'm not a n00b regarding linux; but Home Assistant is still new to me. at first glance it seems like this distro is severely limited(?) OR I just don't see anything obvious. 

Before I completely go the advanced route: has anyone installed it on this os?

**Comment by Gompje** [comment]
I actually found its based on Alpine linux. installing now, will document if it works

**Comment by Gompje** [comment]
I was able to install the deps, make the service but off course, another services system is used. One I'm not familiar with at all.. any help appreciated!

**Comment by Mosibi** [comment]
If you want to run it on Hassio, the best option is to add-on: https://developers.home-assistant.io/docs/add-ons/. But most people have a separate setup, where Hassio is running on a device with more performance and this project (whr_930) running on a separate Pi.

**Comment by tjeerd13** [comment]
> I was able to install the deps, make the service but off course, another services system is used. One I'm not familiar with at all.. any help appreciated!

Hello,

I'm also looking to intergrated the whr into HA OS. Did you get it working?
