### ISSUE TITLE
Error in HA wtw: !include includes/wtw.yaml

### ISSUE THREAD

**Issue by MJPVDH** [Mosibi/whr_930#16]
Hi when i put this and i check configuration i get the following error.

Component error: packages - Integration 'packages' not found. 

I put the src/wtw.yaml in the config/includes directory.

And put the following text in the configuration.yaml 
  packages:
    wtw: !include includes/wtw.yaml

**Comment by Mosibi** [comment]
Which version of HA do you have and which installation method did you use?

**Comment by Mosibi** [comment]
Closed due to missing info
