### ISSUE TITLE
Speed 100%

### ISSUE THREAD

**Issue by AlbertHakvoort** [Mosibi/whr_930#17]
Hi,

When I set the WHR on level 3, the fan speed is max 70%

![image](https://user-images.githubusercontent.com/23001971/122639816-54ebaf00-d0fc-11eb-9190-b3823320690d.png)

When I use the bathroom button, it sets the speed at 100%

![image](https://user-images.githubusercontent.com/23001971/122639843-82d0f380-d0fc-11eb-99c9-09bf956ab476.png)

Is it possible to add a extra level?

**Comment by Mosibi** [comment]
Hi,

I tested it also and in both situations (using HA and the bathroom selector) the level is 70%. To my knowledge there is not an extra level available (see http://www.see-solutions.de/sonstiges/Protokollbeschreibung_ComfoAir.pdf, search for "Stufe setzen").

So somehow in your situation, the '3' is interpreted in another way if it is set by the bathroom then when using the code. You could extend the [get_ventilation_status](https://github.com/Mosibi/whr_930/blob/master/src/whr930.py#L396) function with the extra available information in the "Ventilationsstufe abrufen" command (see PDF) to see if the percentage is changed for '3' when using one of the methods.

I would love to see a pull request which implements that extra information :)

**Comment by AlbertHakvoort** [comment]
https://www.zehnder.nl/download/6410/28751/20601.pdf

![image](https://user-images.githubusercontent.com/23001971/122652469-5e4a3b00-d13f-11eb-8488-243f4a1d5ef3.png)

![image](https://user-images.githubusercontent.com/23001971/122652526-abc6a800-d13f-11eb-98d3-461b6782cf3b.png)

![image](https://user-images.githubusercontent.com/23001971/122720653-0b23d580-d270-11eb-8d8f-87960b96f924.png)

proberly uses the bathroom switch a separate switch to activate the 100% fan

**Comment by Mosibi** [comment]
Stale ticket, closing it. If needed please re-open, preferably with a pull request
