### ISSUE TITLE
Home Assistant has changed MQTT Fans

### ISSUE THREAD

**Issue by joelhaasnoot** [Mosibi/whr_930#19]
The `wtw.yaml` I think now needs to have the fan looks like this:
```
  - platform: mqtt
    name: "Ventilation"
    state_topic: "house/2/attic/wtw/ventilation_level"
    command_topic: "house/2/attic/wtw/set_ventilation_level"
    speed_state_topic: "house/2/attic/wtw/ventilation_level"
    state_value_template: "{{ states.sensor.wtw_ventilation_level.state }}"
    speed_value_template: "{{ states.sensor.wtw_ventilation_level.state }}"
    preset_mode_command_topic: "house/2/attic/wtw/set_ventilation_level"
    preset_mode_command_template: >
        {% if value == "low" %}
            '"1"'
        {% elif value == "medium" %}
            '"2"'
        {% elif value == "high" %}
            '"3"'
        {% else %}
            '"1"'
        {% endif %}
    payload_off: "1"
    payload_on: "3"
    preset_modes:
      - "off"
      - low
      - medium
      - high
  ```
I think this is correct? Let me know what you think - it works for me

**Comment by Mosibi** [comment]
Hi Joel,

Thanks for bringing this up! I was not aware that things where changed in https://www.home-assistant.io/blog/2021/04/07/release-20214/#breaking-changes

Could you make a pull request, with a reference to this issue (https://docs.github.com/en/enterprise-server@3.2/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). This way I can merge it and at the same time, your name is listed as the author of that piece of code.

If a pull-request is to much work, just let me know, then I will make the change

**Comment by joelhaasnoot** [comment]
Will do
