### ISSUE TITLE
Duplicate '07' bytes in data

### ISSUE THREAD

**Issue by Dick-W** [Mosibi/whr_930#2]
Hi,
I'm a newby on Github, so bare with me. Can't get the layout correct ...

According to the protocol, any '07'value in the data part of a respons from the WHR is repeated, without any impact on length or checksum. Upon receipt, such duplicate bytes should be removed.
I detected this because I received strange values for fan speed (RPM).

My solution for serial_command():

```

def serial_command(cmd):
    data = []
    ser.write(cmd)
    time.sleep(2)
    while ser.inWaiting() > 0:
        data.append(ser.read(1).hex())
    if len(data) <= 1: # always expect a valid ACK at least
        return None
    if len(data) == 2 and data[0] == '07' and data[1] == 'f3':
        pass  # just ACK by itself (on all "setting" commands, such as setting ventilation level, command x99)
    else: # valid respons should be at least 10 bytes (ACK + respons with data length = 0)
        if len(data) < 10 or data[0] != '07' or data[1] != 'f3' or data[2] != '07' or data[3] != 'f0' or data[-2] != '07' or data[-1] != '0f':
            warning_msg('Received garbage data, ignored ...')
            return None
        if debug:
            debug_data(data)
        dat_len = int(data[6], 16) # 
        if len(data) > 10 and dat_len > 0:
            for i in range(7,6+dat_len): # REMOVE ANY DOUBLE x07 IN DATA-PART !!!
                if data[i] == '07' and data[i+1] == '07':
                    del data[i+1] ## remove the duplicate
        # CHECK rest of message: correct command, correct checksum ...??
    return data


```

**Comment by Mosibi** [comment]
Dick, this layout makes it almost impossible for me to see what you have changed :) Is it possible for you to create a pull request (see https://help.github.com/articles/about-pull-requests/), that way the changes also have your name on it. If that's not possible, please reformat the code with markdown like so

```lang=python
youre code
````

Can you also do that for the other issue you submitted?

**Comment by Dick-W** [comment]
Yes, I know ….
I didn’t succeed in getting the layout of the code the way it should be.
I don’t have time today to figure out how to correct that and it also will take some time for me to learn how to make the pull request.
So, in the interest of time, maybe this helps:
====================================
def serial_command(cmd):
    data = []
    ser.write(cmd)
    time.sleep(2)
    while ser.inWaiting() > 0:
        data.append(ser.read(1).hex())
# check for ACK and/or matching checksum here .............????
    if len(data) <= 1: # always expect a valid ACK at least
        return None
    if debug:
        debug_data(data)
    if len(data) == 2 and data[0] == '07' and data[1] == 'f3':
        pass  # just ACK by itself (on all "setting" commands, such as setting ventilation level, command x99)
    else: # valid respons should be at least 10 bytes (ACK + respons with data length = 0)
        if len(data) < 10 or data[0] != '07' or data[1] != 'f3' or data[2] != '07' or data[3] != 'f0' or data[-2] != '07' or data[-1] != '0f':
            warning_msg('Received garbage data, ignored ...')
            return None
        dat_len = int(data[6], 16) # 
        if len(data) > 10 and dat_len > 0:
            for i in range(7,6+dat_len): # REMOVE ANY DOUBLE x07 IN DATA-PART !!!
                if data[i] == '07' and data[i+1] == '07':
                    del data[i+1] ## remove the duplicate
        # CHECK rest of message: correct command, correct checksum ...??
    return data
===========================================

The other issue is really simple, replacing two lines of code in the get_fan_status() function.

Best regards,
Dick

**Comment by Dick-W** [comment]
BTW: I just realize that debug_data() won’t work for malformed messages or for just ACK (index out of range)….

**Comment by Dick-W** [comment]
Editted my original comment, now with correct layout and corrected call to debug_data()

**Comment by Mosibi** [comment]
Dick,

In commit https://github.com/Mosibi/whr_930/commit/c4cc7b0242b6ae547d30f34d1944cd41402d09b0 i fixed the issues you submitted. I changed the code/comments a bit. Thank you for the report!
