### ISSUE TITLE
few questions

### ISSUE THREAD

**Issue by 1mfaasj** [Mosibi/whr_930#24]
Hi
I hope you can help me out a bit.

the service whr930.service is running and I get the message "Successfull subscribed to the MQTT topics".
so this is a good sign I think, but I can't see any data in home assistant yet.
I added the wtw.yaml as a package so the entities are visible.
One thing I CAN do is change the "fan.wtw_ventilation" speed. this one works, but I would also would expect to see other data like WTW Outside Temperature and so on.

1. Any idea what i'm missing?
2. Do I have to configure anything else in Home assistant? I have an MQTT docker image running myself and added it as an integration, do I have to set up certain topics? I thought this would not be needed.
![image](https://user-images.githubusercontent.com/71582854/202478803-0e1ced1f-2645-450e-9709-48241a987019.png)

3. is there any way i can check if it works? whether your script receives data, for example?
thanks in advance

**Comment by Mosibi** [comment]
Hi,

You could use the “mosquitto_sub” command to see all, or a selection, of the MQTT messages that your MQTT receives. See https://www.home-assistant.io/integrations/mqtt/#testing-your-setup for more info.

The wtw.yaml provides all configuration that is needed inside HomeAssistant, so extra configuration should not be needed. To see what whr930.py is doing/sending, set debug to true in config.yaml and restart the script. Debug output can be seen with the journalctl command (when running as a systemd service)

**Comment by 1mfaasj** [comment]
thanks for the reply! my issue has been solved by a hardware fix
