### ISSUE TITLE
Problem installing on RPi4 HA

### ISSUE THREAD

**Issue by SgtFoose** [Mosibi/whr_930#26]
Hi, I'm having trouble installing your module since my HA doesn't support "apt-get" commands if I open a terminal editor in HA?
Please advise!

**Comment by Mosibi** [comment]
Hi,

This code is not written to be installed within or next to HA. Technically it is possible, but I would not go for that route if you are not a Linux techie. The best option is to run this on a separate rpi.

**Comment by SgtFoose** [comment]
Ah such a shame, it would be really useful to have it in Home Assistant

**Comment by Mosibi** [comment]
> Ah such a shame, it would be really useful to have it in Home Assistant

For some part yes, but a physical serial connection to the ventilation unit (WHR) is needed and that could be an issue if you do not want to have the machine with HA on it, next to the WHR.
