### ISSUE TITLE
MQTT entity naming

### ISSUE THREAD

**Issue by tieskuh** [Mosibi/whr_930#28]
Hi,

I guess this needs an update of the project, right?

<img width="436" alt="image" src="https://github.com/Mosibi/whr_930/assets/115901851/cd5f2e2e-9641-45cb-bc72-388744378f0c">

https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/

**Comment by Mosibi** [comment]
Ah, I was not aware of this change. Thank you for your this notification, I will dive into it asap

**Comment by tieskuh** [comment]
Hi Mosibi, 

I saw your change. I have set HAAutoDiscovery to true in the config so I cannot change the unique_id in the yaml. For autodiscovery to work next year I think a change is needed in the python script.

**Comment by Mosibi** [comment]
> I saw your change. I have set HAAutoDiscovery to true in the config so I cannot change the unique_id in the yaml. For autodiscovery to work next year I think a change is needed in the python script.

I will put this on my todo list to implement it later this year. A pull request is also welcome! 😄

**Comment by tieskuh** [comment]
Great! No rush. Thanks. 
My Python skills are not that great but if I can find some time I will give it a try.

**Comment by tieskuh** [comment]
Maybe you can reopen the issue for now.
