### ISSUE TITLE
Error in calculation of fan speed

### ISSUE THREAD

**Issue by Dick-W** [Mosibi/whr_930#3]
The calculation of the fan speed (RPM) in get_fan_status() is overly complex and wrong. It ignores leading zeroes in the hex values, leading to incorrect speeds being calculated.

My solution:

Replace the two lines of code
```
        IntakeFanRPM = int(1875000 / int(''.join([str(int(data[9], 16)), str(int(data[10], 16))])))
        ExhaustFanRPM = int(1875000 / int(''.join([str(int(data[11], 16)), str(int(data[12], 16))])))
```

by the following two lines:
```
        IntakeFanRPM = int(1875000 / (int(data[9], 16) * 256 + int(data[10], 16)))
        ExhaustFanRPM = int(1875000 / (int(data[11], 16) * 256 + int(data[12], 16)))
```

**Comment by Mosibi** [comment]
Fixed in commit https://github.com/Mosibi/whr_930/commit/c4cc7b0242b6ae547d30f34d1944cd41402d09b0
