### ISSUE TITLE
Filter Status

### ISSUE THREAD

**Issue by AlbertHakvoort** [Mosibi/whr_930#4]
Hi,

The filter check isn't working on my unit...

![image](https://user-images.githubusercontent.com/23001971/82658111-c077fa00-9c26-11ea-92ad-4f2212a319ff.png)

![image](https://user-images.githubusercontent.com/23001971/82658137-c968cb80-9c26-11ea-827f-b1c188aa0ffd.png)

Does it work on your unit?

**Comment by Mosibi** [comment]
I have seen it working, but that was a while ago.

**Comment by Mosibi** [comment]
Albert,

See the change. I was reading the wrong field for the filter status. Should be fixed now.

**Comment by AlbertHakvoort** [comment]
![image](https://user-images.githubusercontent.com/23001971/82725671-caf5ca80-9cde-11ea-8b89-59af410f58b7.png)

It's working! Thanks

**Comment by Mosibi** [comment]
Top!
