### ISSUE TITLE
Unable to set sensor.wtw_comfort_temperature

### ISSUE THREAD

**Issue by AlbertHakvoort** [Mosibi/whr_930#5]
If I change the sensor.wtw_comfort_temperature it will revert to the setting of the unit itself.

**Comment by Mosibi** [comment]
Albert,
The sensor.wtw_comfort_temperature is just a sensor which is updated by whr930.py to state the current value. To set the temperature, a publish is needed on the topic `house/2/attic/wtw/set_comfort_temperature`. The last commits I did, make it possible to set the value using the GUI.
