### ISSUE TITLE
Warning get_fan_status

### ISSUE THREAD

**Issue by pvandendool** [Mosibi/whr_930#6]
Hi Mosibi,

Dankjwel for the nice work you did!

For all warnings you have the function name and than function ... Only for the get_fan_status its the otherway arround.

27-06-2020 12:28:45 WARNING: get_temp function could not get serial data
27-06-2020 12:28:47 WARNING: get_ventilation_status function could not get serial data
27-06-2020 12:28:49 WARNING: get_filter_status function could not get serial data
27-06-2020 12:28:51 WARNING: function get_fan_status could not get serial data
27-06-2020 12:28:53 WARNING: get_bypass_control function could not get serial data
27-06-2020 12:28:55 WARNING: get_valve_status function could not get serial data
27-06-2020 12:28:57 WARNING: get_status function could not get serial data
27-06-2020 12:28:59 WARNING: get_operating_hours function could not get serial data
27-06-2020 12:29:01 WARNING: get_preheating_status function could not get serial data

**Comment by Mosibi** [comment]
Good catch! I changed the warning message
