### ISSUE TITLE
get_status type wrong

### ISSUE THREAD

**Issue by pvandendool** [Mosibi/whr_930#7]
Hi Mosibi,

I got a error on get_status()

My WHR 930 is a right side type, i received number 2 as a result. According the document of your blog this is indeed number 2.
Only in the status_data is defined as 0.

    status_data = {
        "PreHeatingPresent": {0: False, 1: True},
        "ByPassPresent": {0: False, 1: True},
        "Type": {0: "Right", 1: "Left"},
        "Size": {1: "Large", 2: "Small"},
        "OptionsPresent": {0: False, 1: True},
        "EnthalpyPresent": {0: False, 1: True, 2: "PresentWithoutSensor"},
        "EWTPresent": {0: False, 1: "Managed", 2: "Unmanaged"},
    }

**Comment by Mosibi** [comment]
Thanks for spotting this one. I just changed the source code
