### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'a0'

### ISSUE THREAD

**Issue by iamrellah** [Mosibi/whr_930#9]
Not sure what triggered the error yet, have been running the script without issues since yesterday but it just stopped with the following message. I'll update if/when i'm able to reproduce. In the mean time is this something that look familiar to you and is an actual issue?

```
Traceback (most recent call last):
  File "whr930.py", line 905, in <module>
    sys.exit(main())
  File "whr930.py", line 892, in main
    get_status()
  File "whr930.py", line 753, in get_status
    ActiveStatus1 = int(data[13])  # (0x01 = P10 ... 0x80 = P17)
ValueError: invalid literal for int() with base 10: 'a0'
```

**Comment by Mosibi** [comment]
I do not know what happened there, somehow the value of data[13] was not an integer, but got 'a0'  which is out of range for the ActiveStatus1. What I can do is add an exception for this error so that you get a nice error message the next time
